CREATE DATABASE DIAGNOSTICCENTRE;

DROP DATABASE DIAGNOSTICCENTRE;

CREATE DATABASE PARK;
DROP DATABASE PARK;

CREATE DATABASE RAILWAYTATION;
DROP DATABASE RAILWAYTATION;

CREATE DATABASE SMARTWATCH;
DROP DATABASE SMARTWATCHh;

CREATE SCHEMA FAN;
DROP SCHEMA FAN;

SHOW DATABASES;


