CREATE DATABASE ASSIGNMENT;
/*COMMAND TO USE DATABASE*/

USE ASSIGNMENT;
CREATE TABLE REELS(
  USER_ID INT,
  USER_NAME VARCHAR(10),
  USER_EMAIL VARCHAR(10),
  USER_PHONENUMBER INT,
  SONG_NAME VARCHAR(10),
  TIME_LIMIT VARCHAR(30),
  EFFECTS VARCHAR(3),
  UPLOAD_DATE  DATE,
  NUMBER_OF_LIKES VARCHAR(50),
  NUMBER_OF_FOLLWERS VARCHAR(500)
  );
  CREATE TABLE PIZZA_HUT(
  PIZZA_ID INT PRIMARY KEY,
  PIZZA_NAME VARCHAR(100),
  INGREDIENTS VARCHAR(255),
  CRUST_TYPE VARCHAR(50),
  SIZE VARCHAR(10),
  PRICE DECIMAL(10,2),
  ORDER_DATE DATE,
  NUMBER_OF_ORDERS INT,
  NUMBER_OF_REVIEWS INT
);
CREATE TABLE CAFE_ORDERS (
  ORDER_ID INT PRIMARY KEY,
  CUSTOMER_NAME VARCHAR(100),
  TABLE_NUMBER INT,
  ORDER_DETAILS VARCHAR(255),
  ORDER_DATE DATETIME,
  TOTAL_AMOUNT DECIMAL(10,2),
  PAYMENT_METHOD VARCHAR(50),
  NUMBER_OF_ITEMS INT,
  NUMBER_OF_CUSTOMERS INT
);
CREATE TABLE FROZEN_BOTTLES (
  BOTTLE_ID INT PRIMARY KEY,
  BRAND VARCHAR(50),
  FLAVOR VARCHAR(50),
  SIZE DECIMAL(5,2),
  PRICE DECIMAL(8,2),
  EXPIRATION_DATE DATE,
  STORAGE_CONDITIONS VARCHAR(100),
  QUANTITY INT,
  LAST_RESTOCK_DATE DATE,
  IS_ORGANIC BOOLEAN
);
CREATE TABLE HOTEL (
  ROOM_NUMBER INT PRIMARY KEY,
  ROOM_TYPE VARCHAR(50),
  BEDS INT,
  OCCUPANCY VARCHAR(20),
  RATE DECIMAL(8,2),
  CLEAN_STATUS VARCHAR(20),
  LAST_CLEANED_DATE DATE,
  GUEST_NAME VARCHAR(100),
  CHECKIN_DATE DATE,
  CHECKOUT_DATE DATE
);
CREATE TABLE WESTSIDE_STORE (
  ITEM_ID INT PRIMARY KEY,
  ITEM_NAME VARCHAR(100),
  CATEGORY VARCHAR(50),
  BRAND VARCHAR(50),
  UNIT_PRICE DECIMAL(8,2),
  STOCK_QUANTITY INT,
  DISCOUNT_AVAILABLE BOOLEAN,
  EXPIRATION_DATE DATE,
  LAST_RESTOCK_DATE DATE,
  SUPPLIER VARCHAR(100)
);
CREATE TABLE BURGER_KING_MENU (
  ITEM_ID INT PRIMARY KEY,
  ITEM_NAME VARCHAR(100),
  CATEGORY VARCHAR(50),
  DESCRIPTION VARCHAR(255),
  PRICE DECIMAL(8,2),
  CALORIES INT,
  DIETARY_RESTRICTIONS VARCHAR(100),
  AVAILABLE_SINCE DATE,
  LAST_UPDATED DATE,
  POPULARITY_RANK INT
);
CREATE TABLE CAR_SHOWROOM (
  CAR_ID INT PRIMARY KEY,
  CAR_BRAND VARCHAR(50),
  CAR_MODEL VARCHAR(50),
  YEAR INT,
  COLOR VARCHAR(50),
  PRICE DECIMAL(10,2),
  MILEAGE INT,
  FUEL_TYPE VARCHAR(20),
  TRANSMISSION_TYPE VARCHAR(20),
  AVAILABLE_DATE DATE
);
CREATE TABLE RIDING_GEARS (
  GEAR_ID INT PRIMARY KEY,
  GEAR_TYPE VARCHAR(50),
  BRAND VARCHAR(50),
  SIZE VARCHAR(20),
  COLOR VARCHAR(20),
  MATERIAL VARCHAR(50),
  PRICE DECIMAL(10,2),
  STOCK_QUANTITY INT,
  LAST_RESTOCK_DATE DATE,
  SAFETY_CERTIFICATION VARCHAR(100)
);
CREATE TABLE CHOCOLATES (
  CHOCOLATE_ID INT PRIMARY KEY,
  BRAND VARCHAR(50),
  NAME VARCHAR(100),
  FLAVOR VARCHAR(50),
  TYPE VARCHAR(50),
  WEIGHT DECIMAL(6,2),
  PRICE DECIMAL(8,2),
  STOCK_QUANTITY INT,
  EXPIRATION_DATE DATE,
  ORIGIN_COUNTRY VARCHAR(50)
);
/*COMMAND TO RENAME TABLE*/
ALTER TABLE REELS RENAME TO REELS_STAR;
ALTER TABLE CHOCOLATES RENAME TO CHOCOLATES_FACTORY;
ALTER TABLE CAFE_ORDERS RENAME TO STARBUGS;
ALTER TABLE HOTEL RENAME TO RNR_HOTEL;
ALTER TABLE PIZZA_HUT RENAME TO DOMINOS;

/*COMMAND TO DELETE/DROP COULMN OF THE TABLE*/
ALTER TABLE CHOCOLATE_FACTORY DROP COLUMN WEIGHT;
ALTER TABLE DOMINOS DROP COLUMN CRUST_TYPE;
ALTER TABLE DOMINOS  DROP COLUMN PRICE;

/*COMMAND TO CHANGE DATA TYPE OF COLUMN*/

ALTER TABLE DOMINOS MODIFY COLUMN  INGREDIENTS INT;
ALTER TABLE DOMINOS MODIFY COLUMN  SIZE INT;

/*COMMAND TO CHANGE SIZE OF DATA TYPE OF COLUMN*/
ALTER TABLE DOMINOS MODIFY COLUMN  NUMBER_OF_ORDERS VARCHAR (80);
ALTER TABLE DOMINOS MODIFY COLUMN  NUMBER_OF_REVIEWS VARCHAR (90);

/*COMMAND TO ADD NEW COLUMN TO TABLE9*/
 ALTER TABLE DOMINOS ADD COLUMN  PRIZE VARCHAR (50);
ALTER TABLE DOMINOS ADD COLUMN   RATINGS INT ;

/*COMMAND TO CHANGE NAME OF THE DATABASE*/
RENAME ASSIGNMENT TO TASK_ABSENT;














