CREATE SCHEMA JOINS;
USE JOINS;
CREATE TABLE OTT_PLATFORM(
OTT_ID INT PRIMARY KEY,
OTT_NAME VARCHAR(20),
OTT_LANGUAGE VARCHAR(15),
OTT_SUBSCRIPTION VARCHAR(15)
);
INSERT INTO OTT_PLATFORM VALUES(1,'VOOT','HINDI','3 MONTHS');
INSERT INTO OTT_PLATFORM VALUES(2,'HOTSTAR','KANANADA','8 MONTHS');
INSERT INTO OTT_PLATFORM VALUES(3,'AMAZON PRIME','TAMIL','3 MONTHS');
INSERT INTO OTT_PLATFORM VALUES(4,'JIO CENIMA','TELGU','6 MONTHS');
INSERT INTO OTT_PLATFORM VALUES(5,'NETFLIX','ENGLISH','12 MONTHS');

CREATE TABLE USER_DETAILS(
USER_ID INT PRIMARY KEY,
USER_NAME VARCHAR(20),
USER_EMAILID VARCHAR(16),
CONTACT_NUMBER VARCHAR(10),
PASSWARD VARCHAR(12) NOT NULL UNIQUE,
FOREIGN KEY (OTT_ID) REFERENCES OTT_PLATFORM (OTT_ID)
); 
INSERT INTO USER_DETAILS  VALUES(1,'VIHAN','VVV@GMAIL.COM',8970580783,'VII@3545');
INSERT INTO USER_DETAILS  VALUES(2,'YADUVEER','YaduV@GMAIL.COM',7353466890,'yaduvI@355');
INSERT INTO USER_DETAILS  VALUES(3,'SIRI','SV@gamil.COM',8884903213,'Siri@390');
INSERT INTO USER_DETAILS  VALUES(4,'JEO','Jmax@gmail.COM',8912580983,'jOo@905');
INSERT INTO USER_DETAILS VALUES(5,'MIA','Miaa89@gmail.COM',8861666012,'MssI@4567');
CREATE TABLE FOUNDER_DETAILS(
FOUNDER_ID INT PRIMARY KEY ,
FOUNDER_NAME VARCHAR(20),
FOUNDER_EMAILID VARCHAR (16),
USER_ID INT, 
foreign key(USER_ID) REFERENCES USER_DETAILS(USER_ID)
);
INSERT INTO FOUNDER_DETAILS  VALUES(11,'JACOBO','JACK@gmail.COM',1);
INSERT INTO FOUNDER_DETAILS  VALUES(22,'LEO','lEOOOO@gmail.COM',2);
INSERT INTO FOUNDER_DETAILS  VALUES(33,'MAX','MAXy@gmail.COM',3);
INSERT INTO FOUNDER_DETAILS  VALUES(44,'JACKKIE','JK@gmail.COM',4);
INSERT INTO FOUNDER_DETAILS  VALUES(55,'JACOBO','JACK@gmail.COM',5);
SELECT * FROM OTT_PLATFORM AS OTT , USER_DETAILS;

SELECT * FROM OTT_PLATFORM AS OTT , USER_DETAILS AS USER , FOUNDER_DETAILS AS FOUNDER WHERE OTT.OTT_ID = USER.OTT_ID =  FOUNDER.OTT_ID;
SELECT * FROM OTT_PLATFORM AS OTT  inner join  USER_DETAILS AS USER inner join FOUNDER_DETAILS AS FOUNDER  ON ott.ott_id=user.ott_id AND ott.ott_id=founder.ott_id;
SELECT * FROM OTT_PLATFORM AS OTT LEFT JOIN USER_DETAILS AS USER ON OTT.OTT_ID= USER.OTT_ID WHERE USER_NAME = 'VIVEK';
SELECT * FROM OTT_PLATFORM AS OTT LEFT JOIN USER_DETAILS AS USER ON OTT.OTT_ID = USER.OTT_ID LEFT JOIN FOUNDER_DETAILS AS FOUNDER  ON OTT.OTT_ID = FOUNDER.OTT_ID;
SELECT * FROM OTT_PLATFORM AS OTT RIGHT JOIN USER_DETAILS AS USER ON OTT.OTT_ID = USER.OTT_ID ;
SELECT * FROM OTT_PLATFORM AS OTT RIGHT JOIN USER_DETAILS AS USER ON OTT.OTT_ID = USER.OTT_ID RIGHT JOIN  FOUNDER_DETAILS AS FOUNDER  ON OTT.OTT_ID = FOUNDER.OTT_ID;
SELECT * FROM OTT_PLATFORM AS OTT RIGHT JOIN FOUNDER_DETAILS AS FOUNDER ON OTT.OTT_ID = FOUNDER.OTT_ID;



SELECT DISTINCT (USER_ID) FROM USER_DETAILS;
SELECT* FROM USER_DETAILS ORDER BY  USER_EMAILID;
SELECT* FROM USER_DETAILS ORDER BY USER_EMAILID DESC;
SELECT *FROM USER_DETAILS LIMIT 2 ;