CREATE DATABASE BEE;
USE BEE;

CREATE TABLE BANK(
 BANK_ID INT PRIMARY KEY,
 BANK_NAME VARCHAR(250) NOT NULL UNIQUE,
 IFSC_CODE VARCHAR(20) NOT NULL UNIQUE,
 BRANCH_CODE VARCHAR(100) ,
ADDRESS VARCHAR(100) NOT NULL
);
INSERT INTO BANK VALUES(1,"HDFC","HDFC0000925","HSNBRANCH","BANGLORE");
INSERT INTO BANK VALUES(2,"ICIC","IC2300925","HOSURUBRANCH","MYSORE");
INSERT INTO BANK VALUES(3,"SBI","SBIN123","JPBRANCH","HUBLI");
INSERT INTO BANK VALUES(4,"KOTTAK","KOT56777","BTMBRANCH","MANGLORE");
INSERT INTO BANK VALUES(5,"FEDDRAL","fdrl0001104","HSRBRANCH","HASSAN");

SELECT * FROM BANK;

CREATE TABLE ACCOUNTS(
ACCOUNT_ID INT PRIMARY KEY,
ACCOUNT_BALANCE INT,
ACCOUNT_HOLDER_NAME VARCHAR(100) NOT NULL,
ACCOUNT_HOLDER_ADDRESS VARCHAR(100),
BANK_ID INT,
FOREIGN KEY(BANK_ID) REFERENCES BANK(BANK_ID)
);
   
   INSERT INTO ACCOUNTS VALUES(1,1000,"APUU","BANGLORE",1);
INSERT INTO ACCOUNTS VALUES(2,2500,"RIYA","MYSORE",2);
INSERT INTO ACCOUNTS VALUES(3,3000,"MIYA","HUBLI",3);
INSERT INTO ACCOUNTS VALUES(4,2000,"LEO","MANGLORE",4);
INSERT INTO ACCOUNTS VALUES(5,1200,"MADDY","HASSAN",5);

   SELECT* FROM ACCOUNTS;
SELECT * FROM BANK  AS D, ACCOUNTS AS  A WHERE A.BANK_ID = D.BANK_ID;
SELECT * FROM BANK WHERE BANK_NAME = 'ICIC';
SELECT ACCOUNT_BALANCE FROM ACCOUNTS WHERE ACCOUNT_BALANCE = 1000;

SELECT ACCOUNT_BALANCE FROM ACCOUNTS WHERE ACCOUNT_BALANCE  >= 1000;
SELECT ACCOUNT_BALANCE FROM ACCOUNTS WHERE ACCOUNT_BALANCE  <= 1000;
SELECT ACCOUNT_BALANCE FROM ACCOUNTS WHERE ACCOUNT_BALANCE  = 3000;
SELECT ACCOUNT_BALANCE FROM ACCOUNTS WHERE ACCOUNT_BALANCE  > 2500;



